test script

diff --git a/.github/workflows/private-action.yml b/.github/workflows/private-action.yml
--- a/.github/workflows/private-action.yml
+++ b/.github/workflows/private-action.yml
@@ -30,18 +30,57 @@ jobs:
 
       - name: get base sha with jq
         run: |
-          echo "BASE SHA"
-          [ $GITHUB_EVENT_NAME == "pull_request" ] && \
-            BASE_SHA=$(jq -r .pull_request.base.sha < $GITHUB_EVENT_PATH  | /bin/grep -Po "[a-f0-9]{40}") || \
-            BASE_SHA=$(jq .before < $GITHUB_EVENT_PATH | /bin/grep -Po "[a-f0-9]{40}")
-          echo "HEAD SHA" 
-          [ $GITHUB_EVENT_NAME == "pull_request" ] && \
-            HEAD_SHA="$(echo $GITHUB_SHA | /bin/grep -Po "[a-f0-9]{40}")"  || \
-            HEAD_SHA="$(/usr/bin/jq -r '.after' < "$GITHUB_EVENT_PATH" | /bin/grep -Po "[a-f0-9]{40}")"
+          /bin/echo "::group:: Getting the SHAs"
+          
+          /bin/echo "Trigger event: $GITHUB_EVENT_NAME" 
+          
+          if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then 
+              BASE_SHA="$(/usr/bin/jq -r '.pull_request.base.sha' < "$GITHUB_EVENT_PATH" | /bin/grep -Po "[a-f0-9]{40}")"
+              HEAD_SHA="$(echo $GITHUB_SHA | /bin/grep -Po "[a-f0-9]{40}")" 
+          else 
+              BASE_SHA="$(/usr/bin/jq -r '.before' < "$GITHUB_EVENT_PATH" | /bin/grep -Po "[a-f0-9]{40}")"
+              HEAD_SHA="$(/usr/bin/jq -r '.after' < "$GITHUB_EVENT_PATH" | /bin/grep -Po "[a-f0-9]{40}")"
+          
+          [ -z "$BASE_SHA" ] \
+              && /bin/echo "::error:: Couldn't get the BASE SHA." && exit 1
+          
+          [ -z "$HEAD_SHA" ] \
+              && /bin/echo "::error:: Couldn't get the HEAD SHA." && exit 1
+          
+          /bin/echo "BASE SHA: $BASE_SHA"
+          /bin/echo "HEAD SHA: $HEAD_SHA"
+          
+          /bin/echo "::endgroup::"
+          
+          
+          /bin/echo "::group:: Changing working directory..."
+          
+          pushd "$GITHUB_WORKSPACE" || \
+              (/bin/echo "::error:: Couldn't change the working directory to '$GITHUB_WORKSPACE'" && exit 1)
+          WORKSPACE_PATH="$(/usr/bin/readlink -fn "$INPUT_PATH")"
+          popd 
+          
+          [ ! -d "$WORKSPACE_PATH" ] && \
+              (/bin/echo "::error:: Couldn't resolve the working directory '$WORKSPACE_PATH'" && exit 1 )
+          
+          pushd "$WORKSPACE_PATH" || \
+              (/bin/echo "::error:: change the working directory to '$WORKSPACE_PATH'" && exit 1)
+          
+          /bin/echo "::endgroup::"
+          
+          /bin/echo "::group:: Getting tinted files" 
+          
+          TINTED_FILES="$(/usr/bin/git diff --name-only $BASE_SHA $HEAD_SHA)"
+          
+          [ -z "$TINTED_FILES" || "$?" -ne 0 ] \
+              && /bin/echo "::error:: Couldn't get the tinted files." && exit 1
+          
+          /bin/echo "Tinted files:"
+          /bin/echo "$TINTED_FILES[@]"
+          
+          /bin/echo "::endgroup::" 
 
-          echo "BASE SHA: $BASE_SHA"
-          echo "HEAD SHA: $HEAD_SHA"
-          git diff --name-only $BASE_SHA $HEAD_SHA
+
 
       - name: Get changed files
         id: changed-files
